### ISSUE TITLE
Purge doesn't purge everything ?

### ISSUE THREAD

**Issue by jlvila** [IBM-i2/Intelligence-Analysis-Platform#6] opened 2014-09-18 19:27 UTC
Problem with Direct LOAD. The sequence to reproduce is 
  1) Load the data (-load)
  2) Purge the data from the portal
  3) Load again the data (i.e with the same ID)
        --> Error
4) change the entities & links IDs  and load again, it works !

Probably a problem with the "purge" which not remove all the data

**Comment by stu-w** [comment] 2015-06-12 20:32
Purge is intended to remove all data but to retain the history of the existence of the item. That way if the system events are replayed then the item still exists in the system in a blank form, and (for example) any links created to it are still valid. 

As you say, best practice for your situation is to create new IDs.

I'm marking this as closed as the behavior is as intended.

**Closed by stu-w** 2015-06-12 20:32 UTC
