### ISSUE TITLE
the package doesn't include /mq-java-drivers librairies 

### ISSUE THREAD

**Issue by jlvila** [IBM-i2/Intelligence-Analysis-Platform#4] opened 2014-07-28 19:18 UTC
all is in the title

**Comment by stu-w** [comment] 2015-06-15 08:20
Hello, Jean-Louis. Sorry for the delay in responding. 

As this relates to an old release and is as intended, I'm going to close this issue off. However, if you think it's still a problem could you open a new issue?

Thanks.

**Closed by stu-w** 2015-06-15 08:20 UTC
