### ISSUE TITLE
List of Errors

### ISSUE THREAD

**Issue by brunocnoliveira** [IBM-i2/Intelligence-Analysis-Platform#7] opened 2014-10-02 14:49 UTC
Hello,

Where can I find the list of errors returned by IAP? I need to know all errors that IAP sdk might throws in order to map a set of error codes in my application.

Anyone can help me?

Thanks a lot.

**Comment by stu-w** [comment] 2015-06-12 20:25
Hi, Bruno. Where errors may be returned by API calls the relevant exceptions are listed in the documentation. 

(I'm marking this as closed as the behavior is as intended.)

**Closed by stu-w** 2015-06-12 20:25 UTC
